[2021-12-22 17:31:49,085] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: data_pipeline1.move_file manual__2021-12-22T07:55:18.519597+00:00 [queued]>
[2021-12-22 17:31:49,089] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: data_pipeline1.move_file manual__2021-12-22T07:55:18.519597+00:00 [queued]>
[2021-12-22 17:31:49,089] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-22 17:31:49,089] {taskinstance.py:1242} INFO - Starting attempt 1 of 4
[2021-12-22 17:31:49,089] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-22 17:31:49,098] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): move_file> on 2021-12-22 07:55:18.519597+00:00
[2021-12-22 17:31:49,099] {standard_task_runner.py:52} INFO - Started process 25825 to run task
[2021-12-22 17:31:49,101] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline1', 'move_file', 'manual__2021-12-22T07:55:18.519597+00:00', '--job-id', '118', '--raw', '--subdir', '/home/myamya/project/dockers/airflow/dags/hello_world.py', '--cfg-path', '/tmp/tmp_npm0y4e', '--error-file', '/tmp/tmpz3tex_f_']
[2021-12-22 17:31:49,101] {standard_task_runner.py:77} INFO - Job 118: Subtask move_file
[2021-12-22 17:31:49,119] {logging_mixin.py:109} INFO - Running <TaskInstance: data_pipeline1.move_file manual__2021-12-22T07:55:18.519597+00:00 [running]> on host myamya
[2021-12-22 17:31:49,139] {taskinstance.py:1412} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=yangjae
AIRFLOW_CTX_DAG_ID=data_pipeline1
AIRFLOW_CTX_TASK_ID=move_file
AIRFLOW_CTX_EXECUTION_DATE=2021-12-22T07:55:18.519597+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-22T07:55:18.519597+00:00
[2021-12-22 17:31:49,140] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-12-22 17:31:49,140] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cp /home/myamya/project/image_files/cropped_512_image/* /home/myamya/project/images/real/ | cp /home/myamya/project/image_files/sketched2/* /home/myamya/project/images/sketch/']
[2021-12-22 17:31:49,144] {subprocess.py:85} INFO - Output:
[2021-12-22 17:31:49,146] {subprocess.py:93} INFO - Command exited with return code 0
[2021-12-22 17:31:49,170] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=data_pipeline1, task_id=move_file, execution_date=20211222T075518, start_date=20211222T083149, end_date=20211222T083149
[2021-12-22 17:31:49,233] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-22 17:31:49,288] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
