[2021-12-21 22:23:24,896] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: data_pipeline.face_crop scheduled__2021-12-19T00:07:00+00:00 [queued]>
[2021-12-21 22:23:24,899] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: data_pipeline.face_crop scheduled__2021-12-19T00:07:00+00:00 [queued]>
[2021-12-21 22:23:24,899] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-21 22:23:24,899] {taskinstance.py:1242} INFO - Starting attempt 4 of 4
[2021-12-21 22:23:24,899] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-21 22:23:24,908] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): face_crop> on 2021-12-19 00:07:00+00:00
[2021-12-21 22:23:24,910] {standard_task_runner.py:52} INFO - Started process 95698 to run task
[2021-12-21 22:23:24,912] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'face_crop', 'scheduled__2021-12-19T00:07:00+00:00', '--job-id', '73', '--raw', '--subdir', '/home/myamya/project/dockers/airflow/dags/hello_world.py', '--cfg-path', '/tmp/tmp3w6rix40', '--error-file', '/tmp/tmpmpi7fq3z']
[2021-12-21 22:23:24,912] {standard_task_runner.py:77} INFO - Job 73: Subtask face_crop
[2021-12-21 22:23:24,930] {logging_mixin.py:109} INFO - Running <TaskInstance: data_pipeline.face_crop scheduled__2021-12-19T00:07:00+00:00 [running]> on host myamya
[2021-12-21 22:23:24,946] {taskinstance.py:1412} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=yangjae
AIRFLOW_CTX_DAG_ID=data_pipeline
AIRFLOW_CTX_TASK_ID=face_crop
AIRFLOW_CTX_EXECUTION_DATE=2021-12-19T00:07:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-19T00:07:00+00:00
[2021-12-21 22:23:24,947] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-12-21 22:23:24,947] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'docker run -it -v /home/myamya/project/image_files/:/home/myamya/project/image_files/ google_api:0.8 /bin/bash init.sh ']
[2021-12-21 22:23:24,950] {subprocess.py:85} INFO - Output:
[2021-12-21 22:23:25,720] {subprocess.py:89} INFO - 0
[2021-12-21 22:23:25,720] {subprocess.py:89} INFO - 2
[2021-12-21 22:23:25,720] {subprocess.py:89} INFO - 3
[2021-12-21 22:23:25,720] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/5.jpeg
[2021-12-21 22:23:26,561] {subprocess.py:89} INFO - [Info] /home/myamya/project/image_files/images/5.jpeg: Find face from in position [36, 29, 153, 166] and skew angle [0.54361933, 0.06943509, -1.6302923]
[2021-12-21 22:23:26,623] {subprocess.py:89} INFO - [Info]  /home/myamya/project/image_files/images/5.jpeg: Crop face [36, 29, 153, 166] and write it to file : /home/myamya/project/image_files/cropped_image/5.jpeg
[2021-12-21 22:23:26,623] {subprocess.py:89} INFO - training 1
[2021-12-21 22:23:26,623] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2248.jpg
[2021-12-21 22:23:27,103] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2248.jpg: cannot process file : 'y'
[2021-12-21 22:23:27,104] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2.jpg
[2021-12-21 22:23:27,552] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2.jpg: cannot process file : 'y'
[2021-12-21 22:23:27,552] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2247.jpg
[2021-12-21 22:23:28,023] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2247.jpg: cannot process file : 'y'
[2021-12-21 22:23:28,024] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/4.jpeg
[2021-12-21 22:23:28,583] {subprocess.py:89} INFO - [Info] /home/myamya/project/image_files/images/4.jpeg: Find face from in position [142, 34, 496, 446] and skew angle [1.2299427, 1.4541144, -8.644277]
[2021-12-21 22:23:28,778] {subprocess.py:89} INFO - [Info]  /home/myamya/project/image_files/images/4.jpeg: Crop face [142, 34, 496, 446] and write it to file : /home/myamya/project/image_files/cropped_image/4.jpeg
[2021-12-21 22:23:28,778] {subprocess.py:89} INFO - training 2
[2021-12-21 22:23:28,779] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/1.jpeg
[2021-12-21 22:23:29,461] {subprocess.py:89} INFO - [Info] /home/myamya/project/image_files/images/1.jpeg: Find face from in position [133, 48, 844, 875] and skew angle [-0.20883362, 0.14810006, -3.5433183]
[2021-12-21 22:23:29,824] {subprocess.py:89} INFO - [Info]  /home/myamya/project/image_files/images/1.jpeg: Crop face [133, 48, 844, 875] and write it to file : /home/myamya/project/image_files/cropped_image/1.jpeg
[2021-12-21 22:23:29,824] {subprocess.py:89} INFO - training 3
[2021-12-21 22:23:29,824] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2255.jpg
[2021-12-21 22:23:30,309] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2255.jpg: cannot process file : 'y'
[2021-12-21 22:23:30,309] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2251.jpg
[2021-12-21 22:23:30,767] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2251.jpg: cannot process file : 'y'
[2021-12-21 22:23:30,767] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/3.jpg
[2021-12-21 22:23:31,404] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/3.jpg: cannot process file : 'y'
[2021-12-21 22:23:31,405] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2256.jpg
[2021-12-21 22:23:31,884] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2256.jpg: cannot process file : 'y'
[2021-12-21 22:23:31,884] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/6.jpg
[2021-12-21 22:23:32,420] {subprocess.py:89} INFO - [Info] /home/myamya/project/image_files/images/6.jpg: Find face from in position [171, 19, 364, 244] and skew angle [0.48682502, 0.76570255, -7.8090253]
[2021-12-21 22:23:32,607] {subprocess.py:89} INFO - [Info]  /home/myamya/project/image_files/images/6.jpg: Crop face [171, 19, 364, 244] and write it to file : /home/myamya/project/image_files/cropped_image/6.jpg
[2021-12-21 22:23:32,608] {subprocess.py:89} INFO - training 4
[2021-12-21 22:23:32,608] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2249.jpg
[2021-12-21 22:23:33,063] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2249.jpg: cannot process file : 'y'
[2021-12-21 22:23:33,063] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2245.jpg
[2021-12-21 22:23:33,509] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2245.jpg: cannot process file : 'y'
[2021-12-21 22:23:33,509] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2253.jpg
[2021-12-21 22:23:33,914] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2253.jpg: cannot process file : 'y'
[2021-12-21 22:23:33,914] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2254.jpg
[2021-12-21 22:23:34,391] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2254.jpg: cannot process file : 'y'
[2021-12-21 22:23:34,391] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2252.jpg
[2021-12-21 22:23:34,873] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2252.jpg: cannot process file : 'y'
[2021-12-21 22:23:34,873] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2250.jpg
[2021-12-21 22:23:35,357] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2250.jpg: cannot process file : 'y'
[2021-12-21 22:23:35,358] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/1.jpg
[2021-12-21 22:23:35,846] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/1.jpg: cannot process file : 'y'
[2021-12-21 22:23:35,846] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2246.jpg
[2021-12-21 22:23:36,325] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2246.jpg: cannot process file : 'y'
[2021-12-21 22:23:36,326] {subprocess.py:89} INFO - ## label 1 has 4 of training data
[2021-12-21 22:23:36,326] {subprocess.py:89} INFO - number of datas per label  [4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[2021-12-21 22:23:36,635] {subprocess.py:93} INFO - Command exited with return code 0
[2021-12-21 22:23:36,649] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=face_crop, execution_date=20211219T000700, start_date=20211221T132324, end_date=20211221T132336
[2021-12-21 22:23:36,696] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-21 22:23:36,737] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
