[2021-12-21 22:22:45,840] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: data_pipeline.face_crop scheduled__2021-12-19T00:04:00+00:00 [queued]>
[2021-12-21 22:22:45,844] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: data_pipeline.face_crop scheduled__2021-12-19T00:04:00+00:00 [queued]>
[2021-12-21 22:22:45,844] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-21 22:22:45,844] {taskinstance.py:1242} INFO - Starting attempt 4 of 4
[2021-12-21 22:22:45,844] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-21 22:22:45,852] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): face_crop> on 2021-12-19 00:04:00+00:00
[2021-12-21 22:22:45,854] {standard_task_runner.py:52} INFO - Started process 95388 to run task
[2021-12-21 22:22:45,856] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'face_crop', 'scheduled__2021-12-19T00:04:00+00:00', '--job-id', '70', '--raw', '--subdir', '/home/myamya/project/dockers/airflow/dags/hello_world.py', '--cfg-path', '/tmp/tmpq7szcifg', '--error-file', '/tmp/tmp7gl8nl2r']
[2021-12-21 22:22:45,856] {standard_task_runner.py:77} INFO - Job 70: Subtask face_crop
[2021-12-21 22:22:45,873] {logging_mixin.py:109} INFO - Running <TaskInstance: data_pipeline.face_crop scheduled__2021-12-19T00:04:00+00:00 [running]> on host myamya
[2021-12-21 22:22:45,889] {taskinstance.py:1412} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=yangjae
AIRFLOW_CTX_DAG_ID=data_pipeline
AIRFLOW_CTX_TASK_ID=face_crop
AIRFLOW_CTX_EXECUTION_DATE=2021-12-19T00:04:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-19T00:04:00+00:00
[2021-12-21 22:22:45,889] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-12-21 22:22:45,890] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'docker run -it -v /home/myamya/project/image_files/:/home/myamya/project/image_files/ google_api:0.8 /bin/bash init.sh ']
[2021-12-21 22:22:45,893] {subprocess.py:85} INFO - Output:
[2021-12-21 22:22:46,666] {subprocess.py:89} INFO - 0
[2021-12-21 22:22:46,667] {subprocess.py:89} INFO - 2
[2021-12-21 22:22:46,667] {subprocess.py:89} INFO - 3
[2021-12-21 22:22:46,667] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/5.jpeg
[2021-12-21 22:22:47,508] {subprocess.py:89} INFO - [Info] /home/myamya/project/image_files/images/5.jpeg: Find face from in position [36, 29, 153, 166] and skew angle [0.54361933, 0.06943509, -1.6302923]
[2021-12-21 22:22:47,537] {subprocess.py:89} INFO - [Info]  /home/myamya/project/image_files/images/5.jpeg: Crop face [36, 29, 153, 166] and write it to file : /home/myamya/project/image_files/cropped_image/5.jpeg
[2021-12-21 22:22:47,537] {subprocess.py:89} INFO - training 1
[2021-12-21 22:22:47,537] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2248.jpg
[2021-12-21 22:22:48,068] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2248.jpg: cannot process file : 'y'
[2021-12-21 22:22:48,068] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2.jpg
[2021-12-21 22:22:48,478] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2.jpg: cannot process file : 'y'
[2021-12-21 22:22:48,478] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2247.jpg
[2021-12-21 22:22:49,075] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2247.jpg: cannot process file : 'y'
[2021-12-21 22:22:49,075] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/4.jpeg
[2021-12-21 22:22:49,740] {subprocess.py:89} INFO - [Info] /home/myamya/project/image_files/images/4.jpeg: Find face from in position [142, 34, 496, 446] and skew angle [1.2299427, 1.4541144, -8.644277]
[2021-12-21 22:22:49,904] {subprocess.py:89} INFO - [Info]  /home/myamya/project/image_files/images/4.jpeg: Crop face [142, 34, 496, 446] and write it to file : /home/myamya/project/image_files/cropped_image/4.jpeg
[2021-12-21 22:22:49,904] {subprocess.py:89} INFO - training 2
[2021-12-21 22:22:49,904] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/1.jpeg
[2021-12-21 22:22:50,592] {subprocess.py:89} INFO - [Info] /home/myamya/project/image_files/images/1.jpeg: Find face from in position [133, 48, 844, 875] and skew angle [-0.20883362, 0.14810006, -3.5433183]
[2021-12-21 22:22:50,933] {subprocess.py:89} INFO - [Info]  /home/myamya/project/image_files/images/1.jpeg: Crop face [133, 48, 844, 875] and write it to file : /home/myamya/project/image_files/cropped_image/1.jpeg
[2021-12-21 22:22:50,933] {subprocess.py:89} INFO - training 3
[2021-12-21 22:22:50,933] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2255.jpg
[2021-12-21 22:22:51,412] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2255.jpg: cannot process file : 'y'
[2021-12-21 22:22:51,412] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2251.jpg
[2021-12-21 22:22:52,004] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2251.jpg: cannot process file : 'y'
[2021-12-21 22:22:52,005] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/3.jpg
[2021-12-21 22:22:52,724] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/3.jpg: cannot process file : 'y'
[2021-12-21 22:22:52,724] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2256.jpg
[2021-12-21 22:22:53,188] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2256.jpg: cannot process file : 'y'
[2021-12-21 22:22:53,188] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/6.jpg
[2021-12-21 22:22:53,735] {subprocess.py:89} INFO - [Info] /home/myamya/project/image_files/images/6.jpg: Find face from in position [171, 19, 364, 244] and skew angle [0.48682502, 0.76570255, -7.8090253]
[2021-12-21 22:22:53,890] {subprocess.py:89} INFO - [Info]  /home/myamya/project/image_files/images/6.jpg: Crop face [171, 19, 364, 244] and write it to file : /home/myamya/project/image_files/cropped_image/6.jpg
[2021-12-21 22:22:53,891] {subprocess.py:89} INFO - training 4
[2021-12-21 22:22:53,891] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2249.jpg
[2021-12-21 22:22:54,344] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2249.jpg: cannot process file : 'y'
[2021-12-21 22:22:54,344] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2245.jpg
[2021-12-21 22:22:54,805] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2245.jpg: cannot process file : 'y'
[2021-12-21 22:22:54,805] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2253.jpg
[2021-12-21 22:22:55,271] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2253.jpg: cannot process file : 'y'
[2021-12-21 22:22:55,271] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2254.jpg
[2021-12-21 22:22:55,828] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2254.jpg: cannot process file : 'y'
[2021-12-21 22:22:55,828] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2252.jpg
[2021-12-21 22:22:56,409] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2252.jpg: cannot process file : 'y'
[2021-12-21 22:22:56,409] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2250.jpg
[2021-12-21 22:22:56,927] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2250.jpg: cannot process file : 'y'
[2021-12-21 22:22:56,927] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/1.jpg
[2021-12-21 22:22:57,469] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/1.jpg: cannot process file : 'y'
[2021-12-21 22:22:57,469] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2246.jpg
[2021-12-21 22:22:58,000] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2246.jpg: cannot process file : 'y'
[2021-12-21 22:22:58,000] {subprocess.py:89} INFO - ## label 1 has 4 of training data
[2021-12-21 22:22:58,000] {subprocess.py:89} INFO - number of datas per label  [4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[2021-12-21 22:22:58,225] {subprocess.py:93} INFO - Command exited with return code 0
[2021-12-21 22:22:58,239] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=face_crop, execution_date=20211219T000400, start_date=20211221T132245, end_date=20211221T132258
[2021-12-21 22:22:58,268] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-21 22:22:58,285] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
